#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-sub/sub.h"
#include "data-sub/call.h"
#include "data-sub/cmp.h"
#include "data-mov/push.h"
#include "data-mov/test.h"
#include "data-mov/je.h"
#include "data-mov/jle.h"
#include "data-con/jmp.h"
#include "data-mov/jbe.h"
#include "data-sub/add.h"
#include "data-con/ret.h"
#include "data-mov/leave.h"
#include "data-mov/pop.h"
#include "data-con/ret.h"
#include "data-con/lgdt.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"
